stages:
  - build
  - push
  - deploy

variables:
  DOCKER_USERNAME: "churnobyl"
  BACKEND_IMAGE: "$DOCKER_USERNAME/pipewatch-backend"
  FRONTEND_IMAGE: "$DOCKER_USERNAME/pipewatch-frontend"
  TAG: ${CI_COMMIT_SHA:0:8}

# Backend build and push
build-backend:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-cli
  tags:
    - paori
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop-BE" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
      when: always
  script:
    - docker build -t $BACKEND_IMAGE:$TAG -f backend/Dockerfile backend/
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $BACKEND_IMAGE:$TAG

# Frontend build and push
build-frontend:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-cli
  tags:
    - paori
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop-FE" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
      when: always
  script:
    - docker build -t $FRONTEND_IMAGE:$TAG -f frontend/pipewatch/Dockerfile frontend/pipewatch/
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $FRONTEND_IMAGE:$TAG

# Deploy job to update deployment repository
update-deployment-repo:
  stage: deploy
  image: alpine/git
  before_script:
    - apk add --no-cache bash sed
  tags:
    - paori
  rules:
    - if: '($CI_COMMIT_REF_NAME == "develop-FE" || $CI_COMMIT_REF_NAME == "develop-BE") && $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  script:
    - git clone https://$GITLAB_USER:$GITLAB_TOKEN@lab.ssafy.com/tjdcjfals3/s11p31a506-deploy.git
    - cd s11p31a506-deploy
    - 'sed -i "s|tag:.*|tag: \"$TAG\"|g" backend/values.yaml'
    - 'sed -i "s|tag:.*|tag: \"$TAG\"|g" frontend/values.yaml'
    - git add .
    - git commit -m "Update images to $TAG"
    - git push origin master
