server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: pipewatch

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_USER_NAME}
    password: ${GOOGLE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000 #인증 코드 만료시간
  config:
    import: optional:file:.env[.properties]

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

api_prefix: /api

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
jwt:
  secret: ${JWT_SECRET}
  access:
    expiration:  1800 # 30분
  refresh:
    expiration: 1209600 # 2주