server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: pipewatch

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  config:
    import: optional:file:.env[.properties]

